CC = g++
VER = '-std=c++11'

# Compiled program name
TARGET = theCalendar

all:
	$(CC) $(VER) -o ./$(TARGET) main.cpp calendar.cpp year.cpp month.cpp day.cpp todo.cpp
	./$(TARGET)
clean:
	rm ./$(TARGET)
